[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/posts"
to = "/"
status = 307

[[redirects]]
from = "/tags"
to = "/"
status = 307